spring:
    datasource:
        url: jdbc:mysql://172.17.0.4:3306?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
        username: root
        password: sire
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8


mybatis:
    mapperLocations: classpath:mybatis/mapper/*.xml
    config-location: classpath:mybatis/mybatis-config.xml
    typeAliasesPackage: com.sire.footprint

storage:
     root:
        dir: /usr/storage

endpoints:
  health:
    sensitive: false
  mappings:
    sensitive: false
  trace:
    sensitive: false
  metrics:
    sensitive: false
  env:
    sensitive: false
  configprops:
    sensitive: false
  beans:
    sensitive: false
  autoconfig:
    sensitive: false